nohup: ignoring input
/home/xiao/miniconda3/envs/torch/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/xiao/miniconda3/envs/torch/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
> /home/xiao/code/CS5242/CS5242/dataset.py(26)__init__()
-> self.transform = transforms.Compose([
(Pdb) Traceback (most recent call last):
  File "/home/xiao/code/CS5242/CS5242/main.py", line 145, in <module>
    dataset = ImageDataset(base_dir + config["mode"],device=device,config=config,train=True)
  File "/home/xiao/code/CS5242/CS5242/dataset.py", line 26, in __init__
    self.transform = transforms.Compose([
  File "/home/xiao/code/CS5242/CS5242/dataset.py", line 26, in __init__
    self.transform = transforms.Compose([
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/bdb.py", line 114, in dispatch_line
    self.user_line(frame)
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/pdb.py", line 262, in user_line
    self.interaction(frame, None)
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/pdb.py", line 357, in interaction
    self._cmdloop()
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/pdb.py", line 322, in _cmdloop
    self.cmdloop()
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
OSError: [Errno 9] Bad file descriptor
